name: Checks JDK version for minor updates

on:
  workflow_dispatch:

env:
  JDK_VERSION: 21.0.0
  JDK_VENDOR: zulu

jobs:
  jdk-current:
    name: Check out current version
    runs-on: ubuntu-latest
    outputs:
      jdk-date: ${{ steps.get-date.outputs.jdk-date}}
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: 21.0.0
          distribution: zulu
          check-latest: false
      - name: Read JAVA_VERSION_DATE and store in env variable
        id: get-date
        run: |
          line=$(cat ${JAVA_HOME}/release | grep "JAVA_VERSION_DATE=\"")
          regex="$JAVA_VERSION_DATE=\"([0-9-]+)\""
          if [[ $line =~ $regex ]]
          then
          echo "jdk-date=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          fi
  jdk-latest:
    name: Checkout latest jdk version
    runs-on: ubuntu-latest
    outputs:
      jdk-date: ${{ steps.get-date.outputs.jdk-date}}
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: zulu
          check-latest: true
      - name: Read JAVA_VERSION_DATE and store in env variable
        id: get-date
        run: |
          line=$(cat ${JAVA_HOME}/release | grep "JAVA_VERSION_DATE=\"")
          regex="$JAVA_VERSION_DATE=\"([0-9-]+)\""
          if [[ $line =~ $regex ]]
          then
          echo "jdk-date=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          fi
  notify:
    name: Notifies for jdk update
    runs-on: ubuntu-latest
    needs: [jdk-current, jdk-latest]
    if: ${{ needs.jdk-latest.outputs.jdk-date }} > ${{ needs.jdk-current.outputs.jdk-date }}
    steps:
      - name: do something
        run: echo "Hello"