name: Build

on:
  workflow_dispatch:
   inputs:
     confirm:
      description: 'Are yeh sure?'
      required: true
      default: 'no' 

env:
  JAVA_VERSION: 16

jobs: 
  win-msi:
    name: Do stuff on Windows
    runs-on: windows-latest
    steps:
      - name: Two commands, Single line each, pwsh
        run: |
          $Env:JpackageWixWizardResources = (Get-Location).Path + "\dist\win\resources" 
          gci
      - name: Two commands, Second Multiline, pwsh
        run: |
          $Env:JpackageWixWizardResources = (Get-Location).Path + "\dist\win\resources" 
          echo `
          "Hello"
      - name: Two commands, Second Multiline, bash 
        run: |
          echo "Single Line"
          echo \
          "Multi Line"
        shell: bash
      - name: Use working dir
        run: |
          test="$PWD/add/iotional/path"
          echo \
          $test
        shell: bash

    