name: Second Flow 

on:
  workflow_run:
    workflows: ["First Flow"]
    tags:
      - '*'

jobs:
  greetings:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Greet Myself"
        run: |
          echo "Hello Meee!"