name: Check up on secret 

on:
  workflow_dispatch:
    inputs:
      yolo:
        description: yolo
        type: boolean

jobs:
  checksecret:
    runs-on: ubuntu-latest
    env:
      SECRET_VAR: ${{ secrets.SUPER_SECRET }}
    steps:
      - name: Do some mumbo jumbo with the secret
        id: test123
        if: startsWith(env.SECRET_VAR, 'token')
        run: echo "Hooray"
      - name: Fail, if the step before was not executed
        if: steps.test123.outcome == 'skipped'
        run: exit 1
